version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_test
      MYSQL_USER: root
    expose:
      - "3306"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  bot:
    build: .
    links:
      - db
    volumes:
      # write your beproudbot path
      # sample
      # - /Users/wan/Work/bp/beproudbot:/beproudbot
      - /Users/wan/work/bott:/bot
