version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - /var/lib/mysql
    container_name: mysql-datastore
    tty: true # 起動していなくても問題ないが、誤って削除しないように立ち上げとく
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: beproudbot
      MYSQL_USER: root
      TZ: "Asia/Tokyo"
    expose:
      - "3306"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    volumes_from:
      - datastore
    container_name: mysql
  app:
    build: .
    links:
      - db
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      # write your beproudbot path
      # sample
      - /Users/wan/Work/bp/beproudbot:/beproudbot
#       - /Users/wan/work/bott:/bot
    volumes_from:
      - datastore
    container_name: bot
